commonLabels:
  cluster: production-loyalty
  vendor: tada
controller:
  ingressClass: admin-ui-nginx
  ingressClassResource:
    controllerValue: k8s.io/admin-ui-ingress-nginx
    default: false
    enabled: true
    name: admin-ui-nginx
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: prometheus
      enabled: true
  replicaCount: 3
  service:
    annotations:
      cloud.google.com/load-balancer-type: Internal
      cloud.google.com/neg: '{"exposed_ports":{"80":{"name":"ingress-nginx-internal-80-neg-http"}}}'
      networking.gke.io/load-balancer-type: Internal
defaultBackend:
  enabled: false
fullNameOverride: admin-ui-nginx
