backend:
  replicas: 0
chunksCache:
  enabled: false
deploymentMode: SingleBinary
gateway:
  enabled: false
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  limits_config:
    allow_structured_metadata: false
    ingestion_burst_size_mb: 1000
    ingestion_rate_mb: 10000
    max_cache_freshness_per_query: 10m
    query_timeout: 300s
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    split_queries_by_interval: 15m
    volume_enabled: true
  rulerConfig:
    enable_api: true
    remote_write:
      client:
        url: http://prometheus-prometheus.monitoring:9090/api/v1/write
      enabled: true
    ring:
      kvstore:
        store: inmemory
    rule_path: /tmp/loki/rules
    storage:
      local:
        directory: /var/loki/rules
      type: local
    wal:
      dir: /tmp/loki/wal
  schemaConfig:
    configs:
    - from: "2024-10-01"
      index:
        period: 24h
        prefix: index_
      object_store: gcs
      schema: v13
      store: tsdb
  storage:
    bucketNames:
      chunks: adira-loki-store
      ruler: adira-loki-store
  storage_config:
    gcs:
      bucket_name: admf-new-loyalty-prod
    tsdb_shipper:
      active_index_directory: /tmp/loki/index
      cache_location: /tmp/loki/index_cache
lokiCanary:
  enabled: false
read:
  replicas: 0
resultsCache:
  enabled: false
singleBinary:
  extraEnv:
  - name: GOMEMLIMIT
    value: 1750MiB
  replicas: 1
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 450m
      memory: 2Gi
test:
  enabled: false
write:
  replicas: 0
