apiVersion: v1
data:
  ADIRA_TRANSLATOR_SERVER_URL: aHR0cDovL2FkaXJhLXRyYW5zbGF0b3ItYXBpLXNlcnZpY2UubG95YWx0eS1wcm9kLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDA=
  AUTH_MAX_DELAY_RETRY_MS: NTA=
  AUTH_MAX_RETRY_NUMBER: Mw==
  CAMPAIGN_SERVER_URL: aHR0cDovL2NhbXBhaWduLWFwcC5sb3lhbHR5LXByb2Quc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMA==
  ELASTIC_APM_ACTIVE: dHJ1ZQ==
  ELASTIC_APM_ENVIRONMENT: bmV3LWxveWFsdHktc3lzdGVtLXByb2Q=
  ELASTIC_APM_SERVER_URL: aHR0cDovLzEwLjkxLjEuMTg6ODIwMA==
  ENABLE_MASK_LOGGER: MQ==
  ENABLE_TADA_REQ_ID: MQ==
  EVOUCHER_SERVER_URL: aHR0cDovL2V2b3VjaGVyLWFwcC5sb3lhbHR5LXByb2Quc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMA==
  FLOWMAN_SERVER_URL: aHR0cDovL2Zsb3dtYW4tYXBwLmxveWFsdHktcHJvZC5zdmMuY2x1c3Rlci5sb2NhbDozMDAw
  GENERATOR_TADA_REQ_ID: eGlk
  IDENTITY_SERVER_URL: aHR0cDovL2lkZW50aXR5LWFwaS1zZXJ2aWNlLmxveWFsdHktcHJvZC5zdmMuY2x1c3Rlci5sb2NhbDozMDAw
  KEEP_ALIVE_MODE: c2hvcnRjb25u
  MEMBERSHIP_ADMIN_SERVER_URL: aHR0cDovL21lbWJlcnNoaXAtYWRtaW4tYXBpLXNlcnZpY2UubG95YWx0eS1wcm9kLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDA=
  MEMBERSHIP_SERVER_URL: aHR0cDovL21lbWJlcnNoaXAtYXBpLXNlcnZpY2UubG95YWx0eS1wcm9kLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDA=
  PORT: MzAwMA==
  PROXY_DELAY_RETRY_MS: NTA=
  PROXY_RETRY_NUMBER: Mw==
  REPORTER_SERVER_URL: aHR0cDovL3JlcG9ydC1ibG9jay1hcHAubG95YWx0eS1wcm9kLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDA=
  REWARD_CATALOG_SERVER_URL: aHR0cDovL3Jld2FyZC1jYXRhbG9nLWFwcC5sb3lhbHR5LXByb2Quc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMA==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ADIRA_TRANSLATOR_SERVER_URL":"aHR0cDovL2FkaXJhLXRyYW5zbGF0b3ItYXBpLXNlcnZpY2UubG95YWx0eS1wcm9kLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDA=","AUTH_MAX_DELAY_RETRY_MS":"NTA=","AUTH_MAX_RETRY_NUMBER":"Mw==","CAMPAIGN_SERVER_URL":"aHR0cDovL2NhbXBhaWduLWFwcC5sb3lhbHR5LXByb2Quc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMA==","ELASTIC_APM_ACTIVE":"dHJ1ZQ==","ELASTIC_APM_ENVIRONMENT":"bmV3LWxveWFsdHktc3lzdGVtLXByb2Q=","ELASTIC_APM_SERVER_URL":"aHR0cDovLzEwLjkxLjEuMTg6ODIwMA==","ENABLE_MASK_LOGGER":"MQ==","ENABLE_TADA_REQ_ID":"MQ==","EVOUCHER_SERVER_URL":"aHR0cDovL2V2b3VjaGVyLWFwcC5sb3lhbHR5LXByb2Quc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMA==","FLOWMAN_SERVER_URL":"aHR0cDovL2Zsb3dtYW4tYXBwLmxveWFsdHktcHJvZC5zdmMuY2x1c3Rlci5sb2NhbDozMDAw","GENERATOR_TADA_REQ_ID":"eGlk","IDENTITY_SERVER_URL":"aHR0cDovL2lkZW50aXR5LWFwaS1zZXJ2aWNlLmxveWFsdHktcHJvZC5zdmMuY2x1c3Rlci5sb2NhbDozMDAw","KEEP_ALIVE_MODE":"c2hvcnRjb25u","MEMBERSHIP_ADMIN_SERVER_URL":"aHR0cDovL21lbWJlcnNoaXAtYWRtaW4tYXBpLXNlcnZpY2UubG95YWx0eS1wcm9kLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDA=","MEMBERSHIP_SERVER_URL":"aHR0cDovL21lbWJlcnNoaXAtYXBpLXNlcnZpY2UubG95YWx0eS1wcm9kLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDA=","PORT":"MzAwMA==","PROXY_DELAY_RETRY_MS":"NTA=","PROXY_RETRY_NUMBER":"Mw==","REPORTER_SERVER_URL":"aHR0cDovL3JlcG9ydC1ibG9jay1hcHAubG95YWx0eS1wcm9kLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDA=","REWARD_CATALOG_SERVER_URL":"aHR0cDovL3Jld2FyZC1jYXRhbG9nLWFwcC5sb3lhbHR5LXByb2Quc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMA=="},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":null,"name":"api-gateway-env","namespace":"loyalty-prod"}}
  creationTimestamp: "2024-11-15T10:15:10Z"
  name: api-gateway-env
  namespace: loyalty-prod
  resourceVersion: "29633622"
  uid: ba3d408d-628b-4b77-94fb-873c888bd053
type: Opaque
