apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2024-11-07T03:02:44Z"
  labels:
    managed-by: prometheus-operator
  name: alertmanager-prometheus-alertmanager-tls-assets-0
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Alertmanager
    name: prometheus-alertmanager
    uid: c54f76ac-0ae0-4f56-8e91-2a6ebccc1a6a
  resourceVersion: "20716838"
  uid: fb53d815-c76f-462a-ac64-badb59857fb5
type: Opaque
