apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2024-11-07T03:02:44Z"
  labels:
    managed-by: prometheus-operator
  name: prometheus-prometheus-prometheus-tls-assets-0
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: prometheus-prometheus
    uid: eb85a259-4629-495d-9b99-a9d3d1da0be7
  resourceVersion: "20716831"
  uid: e8550200-4bff-42a0-9a2e-4a4697ec9bcb
type: Opaque
