apiVersion: v1
data:
  datasource-syncer: gke.gcr.io/prometheus-engine/datasource-syncer:v0.13.1-gke.0@sha256:978bd1fa19a70a2aa729e93f7e88b40220f3a2eb47c1a6dd7217fba6f364a01c
  example-app: gke.gcr.io/prometheus-engine/example-app:v0.13.1-gke.0@sha256:87cdc591aed871b1febb7b81615a44c0c6db32fc9e428738171907e0348a07b4
  frontend: gke.gcr.io/prometheus-engine/frontend:v0.13.1-gke.0@sha256:5fb82edadc729cabda578db193224a56af5684e4ae4d282ab5966dec82bdf052
kind: ConfigMap
metadata:
  annotations:
    components.gke.io/component-name: managed-prometheus
    components.gke.io/component-version: 0.13.1-gke.0
    components.gke.io/image-map: Images deployed by operator
    components.gke.io/layer: addon
  creationTimestamp: "2024-10-18T07:11:30Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: config-images
  namespace: gmp-system
  resourceVersion: "875"
  uid: 5a4a9aaf-b02a-4501-b677-91b1e6c58704
