apiVersion: v1
data:
  config.yaml: |
    global: {}
    scrape_configs:
        - job_name: ClusterNodeMonitoring/gmp-kubelet-cadvisor/metrics/cadvisor
          honor_timestamps: false
          scrape_interval: 30s
          scrape_timeout: 30s
          metrics_path: /metrics/cadvisor
          scheme: https
          authorization:
            credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: false
          follow_redirects: false
          enable_http2: false
          relabel_configs:
            - target_label: job
              replacement: gmp-kubelet-cadvisor
              action: replace
            - source_labels: [__meta_kubernetes_node_name]
              target_label: node
              action: replace
            - source_labels: [__meta_kubernetes_node_name]
              target_label: instance
              replacement: $1:metrics/cadvisor
              action: replace
            - target_label: project_id
              replacement: new-loyalty-439001
              action: replace
            - target_label: location
              replacement: asia-southeast2
              action: replace
            - target_label: cluster
              replacement: loyalty-prod
              action: replace
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: container_cpu_cfs_periods_total|container_cpu_cfs_throttled_periods_total|container_cpu_usage_seconds_total|container_fs_limit_bytes|container_fs_read_seconds_total|container_fs_reads_bytes_total|container_fs_reads_total|container_fs_usage_bytes|container_fs_write_seconds_total|container_fs_writes_bytes_total|container_fs_writes_total|container_memory_rss|container_memory_working_set_bytes|container_network_receive_bytes_total|container_network_receive_packets_dropped_total|container_network_receive_packets_total|container_network_transmit_bytes_total|container_network_transmit_packets_dropped_total|container_network_transmit_packets_total
              action: keep
          kubernetes_sd_configs:
            - role: node
              kubeconfig_file: ""
              follow_redirects: true
              enable_http2: true
              selectors:
                - role: node
                  field: metadata.name=$(NODE_NAME)
        - job_name: ClusterNodeMonitoring/gmp-kubelet-metrics/metrics
          honor_timestamps: false
          scrape_interval: 30s
          scrape_timeout: 30s
          metrics_path: /metrics
          scheme: https
          authorization:
            credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: false
          follow_redirects: false
          enable_http2: false
          relabel_configs:
            - target_label: job
              replacement: gmp-kubelet-metrics
              action: replace
            - source_labels: [__meta_kubernetes_node_name]
              target_label: node
              action: replace
            - source_labels: [__meta_kubernetes_node_name]
              target_label: instance
              replacement: $1:metrics
              action: replace
            - target_label: project_id
              replacement: new-loyalty-439001
              action: replace
            - target_label: location
              replacement: asia-southeast2
              action: replace
            - target_label: cluster
              replacement: loyalty-prod
              action: replace
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: kubelet_certificate_manager_server_ttl_seconds|kubelet_node_name|kubelet_pleg_relist_duration_seconds.*|kubelet_pod_worker_duration_seconds.*|kubelet_running_containers|kubelet_running_pods|kubelet_runtime_operations_total|kubelet_volume_stats_available_bytes|kubelet_volume_stats_capacity_bytes|kubelet_volume_stats_inodes|kubelet_volume_stats_inodes_free|kubelet_volume_stats_inodes_used|kubelet_volume_stats_used_bytes
              action: keep
          kubernetes_sd_configs:
            - role: node
              kubeconfig_file: ""
              follow_redirects: true
              enable_http2: true
              selectors:
                - role: node
                  field: metadata.name=$(NODE_NAME)
        - job_name: ClusterPodMonitoring/kube-state-metrics/k8s-objects
          honor_timestamps: false
          scrape_interval: 30s
          scrape_timeout: 30s
          metrics_path: /metrics
          follow_redirects: true
          enable_http2: true
          relabel_configs:
            - target_label: project_id
              replacement: new-loyalty-439001
              action: replace
            - target_label: location
              replacement: asia-southeast2
              action: replace
            - target_label: cluster
              replacement: loyalty-prod
              action: replace
            - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
              regex: gke-managed-kube-state-metrics
              action: keep
            - target_label: job
              replacement: kube-state-metrics
              action: replace
            - source_labels: [__meta_kubernetes_pod_phase]
              regex: (Failed|Succeeded)
              action: drop
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: __tmp_instance
              action: replace
            - source_labels: [__meta_kubernetes_pod_controller_kind, __meta_kubernetes_pod_node_name]
              regex: DaemonSet;(.*)
              target_label: __tmp_instance
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              regex: k8s-objects
              action: keep
            - source_labels: [__tmp_instance, __meta_kubernetes_pod_container_port_name]
              regex: (.+);(.+)
              target_label: instance
              replacement: $1:$2
              action: replace
          metric_relabel_configs:
            - source_labels: [namespace]
              regex: gke-managed-.*
              action: drop
          kubernetes_sd_configs:
            - role: pod
              kubeconfig_file: ""
              follow_redirects: true
              enable_http2: true
              selectors:
                - role: pod
                  field: spec.nodeName=$(NODE_NAME)
kind: ConfigMap
metadata:
  creationTimestamp: "2024-10-18T07:12:42Z"
  name: collector
  namespace: gmp-system
  resourceVersion: "2090"
  uid: cb3a8d3f-3c65-470a-ba3c-94fd71cbfa08
