apiVersion: v1
data:
  konnectivity-agent-metrics-collector-config-data: |
    # proto-file: cloud/kubernetes/metrics/components/collector/config/collector.proto
    # proto-message: Config

    scrape_target: {
      url: "http://localhost:8093/metrics"
      target_name: "konnectivity-agent"
    }
    export_target: {
      endpoint: "monitoring.googleapis.com:443"
    }
    metrics: {
      source_metric_name: "go_goroutines"
      export_metric_name: "kubernetes.io/internal/addons/konnectivitynetworkproxy_agent/go_goroutines"
      resource_metadata: {
        metric_schema: SCHEMA_K8S_CONTAINER
      }
      value_type: VALUE_TYPE_INT64
      metric_kind: METRIC_KIND_GAUGE
      description: "The current number of goroutines in existence in the Konnectivity proxy agent."
      unit: "count"
    }
    metrics: {
      source_metric_name: "process_start_time_seconds"
      export_metric_name: "kubernetes.io/internal/addons/konnectivitynetworkproxy_agent/process_start_time_seconds"
      resource_metadata: {
        metric_schema: SCHEMA_K8S_CONTAINER
      }
      value_type: VALUE_TYPE_INT64
      metric_kind: METRIC_KIND_GAUGE
      description: "Start time of the Konnectivity proxy agent since unix epoch in seconds."
      unit: "seconds"
    }
    metrics: {
      source_metric_name: "process_virtual_memory_bytes"
      export_metric_name: "kubernetes.io/internal/addons/konnectivitynetworkproxy_agent/process_virtual_memory_bytes"
      resource_metadata: {
        metric_schema: SCHEMA_K8S_CONTAINER
      }
      value_type: VALUE_TYPE_DOUBLE
      metric_kind: METRIC_KIND_GAUGE
      description: "Virtual memory (bytes) used by the Konnectivity proxy agent."
      unit: "By"
    }
    metrics: {
      source_metric_name: "konnectivity_network_proxy_agent_dial_duration_seconds"
      export_metric_name: "kubernetes.io/internal/addons/konnectivitynetworkproxy_agent/konnectivity_network_proxy_agent_dial_duration_seconds"
      resource_metadata: {
        metric_schema: SCHEMA_K8S_CONTAINER
      }
      value_type: VALUE_TYPE_DISTRIBUTION
      metric_kind: METRIC_KIND_CUMULATIVE
      description: "The latency of the Konnectivity proxy agent dialing to the final endpoint, in seconds."
      unit: "seconds"
    }
    metrics: {
      source_metric_name: "konnectivity_network_proxy_agent_server_connection_failure_count"
      export_metric_name: "kubernetes.io/internal/addons/konnectivitynetworkproxy_agent/konnectivity_network_proxy_agent_server_connection_failure_count"
      resource_metadata: {
        metric_schema: SCHEMA_K8S_CONTAINER
      }
      value_type: VALUE_TYPE_INT64
      metric_kind: METRIC_KIND_CUMULATIVE
      metric_labels: {
        source_name: "direction"
        type: METRIC_LABEL_STRING
        description: "Direction of the connection, either from_server or to_server"
      }
      description: "Count of failures of Konnectivity proxy agent sending to or receiving from the proxy server."
      unit: "1"
    }
    metrics: {
      source_metric_name: "konnectivity_network_proxy_agent_endpoint_dial_failure_total"
      export_metric_name: "kubernetes.io/internal/addons/konnectivitynetworkproxy_agent/konnectivity_network_proxy_agent_endpoint_dial_failure_total"
      resource_metadata: {
        metric_schema: SCHEMA_K8S_CONTAINER
      }
      value_type: VALUE_TYPE_INT64
      metric_kind: METRIC_KIND_CUMULATIVE
      metric_labels: {
        source_name: "reason"
        type: METRIC_LABEL_STRING
        description: "reason"
      }
      description: "Number of failures dialing the remote endpoint, by reason (example: timeout)."
      unit: "count"
    }
    metrics: {
      source_metric_name: "konnectivity_network_proxy_agent_open_server_connections"
      export_metric_name: "kubernetes.io/internal/addons/konnectivitynetworkproxy_agent/konnectivity_network_proxy_agent_open_server_connections"
      resource_metadata: {
        metric_schema: SCHEMA_K8S_CONTAINER
      }
      value_type: VALUE_TYPE_INT64
      metric_kind: METRIC_KIND_GAUGE
      description: "Current number of open server connections."
      unit: "count"
    }
    metrics: {
      source_metric_name: "konnectivity_network_proxy_agent_open_endpoint_connections"
      export_metric_name: "kubernetes.io/internal/addons/konnectivitynetworkproxy_agent/konnectivity_network_proxy_agent_open_endpoint_connections"
      resource_metadata: {
        metric_schema: SCHEMA_K8S_CONTAINER
      }
      value_type: VALUE_TYPE_INT64
      metric_kind: METRIC_KIND_GAUGE
      description: "Current number of open endpoint connections."
      unit: "count"
    }
    metrics: {
      source_metric_name: "konnectivity_network_proxy_agent_stream_packets_total"
      export_metric_name: "kubernetes.io/internal/addons/konnectivitynetworkproxy_agent/konnectivity_network_proxy_agent_stream_packets_total"
      resource_metadata: {
        metric_schema: SCHEMA_K8S_CONTAINER
      }
      value_type: VALUE_TYPE_INT64
      metric_kind: METRIC_KIND_CUMULATIVE
      metric_labels: {
        source_name: "packet_type"
        type: METRIC_LABEL_STRING
        description: "packet_type"
      }
      metric_labels: {
        source_name: "segment"
        type: METRIC_LABEL_STRING
        description: "segment"
      }
      description: "Count of packets processed, by segment and packet type (example: from_client, DIAL_REQ)."
      unit: "count"
    }
    metrics: {
      source_metric_name: "konnectivity_network_proxy_agent_stream_errors_total"
      export_metric_name: "kubernetes.io/internal/addons/konnectivitynetworkproxy_agent/konnectivity_network_proxy_agent_stream_errors_total"
      resource_metadata: {
        metric_schema: SCHEMA_K8S_CONTAINER
      }
      value_type: VALUE_TYPE_INT64
      metric_kind: METRIC_KIND_CUMULATIVE
      metric_labels: {
        source_name: "code"
        type: METRIC_LABEL_STRING
        description: "code"
      }
      metric_labels: {
        source_name: "packet_type"
        type: METRIC_LABEL_STRING
        description: "packet_type"
      }
      metric_labels: {
        source_name: "segment"
        type: METRIC_LABEL_STRING
        description: "segment"
      }
      description: "Count of gRPC stream errors, by segment, grpc Code, packet type. (example: from_agent, Code.Unavailable, DIAL_RSP)."
      unit: "count"
    }
kind: ConfigMap
metadata:
  annotations:
    components.gke.io/component-name: konnectivitynetworkproxy-combined
    components.gke.io/component-version: 1.12.6
    components.gke.io/layer: addon
  creationTimestamp: "2024-10-18T07:11:18Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: konnectivity-agent-metrics-collector-config-map
  namespace: kube-system
  resourceVersion: "661"
  uid: 8478cf90-a666-4ed6-93d1-6d38be054309
