apiVersion: v1
data:
  ladder: |-
    {
      "coresToReplicas": [],
      "nodesToReplicas":
      [
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [10, 8],
        [100, 12],
        [250, 18],
        [500, 25],
        [2000, 50],
        [5000, 100]
      ]
    }
kind: ConfigMap
metadata:
  annotations:
    components.gke.io/component-name: konnectivitynetworkproxy-combined
    components.gke.io/component-version: 1.12.6
    components.gke.io/layer: addon
  creationTimestamp: "2024-10-18T07:11:17Z"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: konnectivity-agent-autoscaler-config
  namespace: kube-system
  resourceVersion: "645"
  uid: bdbd0560-7fd4-4c14-bbd1-1404cc63580e
