apiVersion: v1
data:
  config.yaml: |2

    auth_enabled: false
    bloom_build:
      builder:
        planner_address: ""
      enabled: false
    bloom_gateway:
      client:
        addresses: ""
      enabled: false
    common:
      compactor_address: 'http://loki-single:3100'
      path_prefix: /var/loki
      replication_factor: 1
      storage:
        s3:
          bucketnames: adira-loki-store
          insecure: false
          s3forcepathstyle: false
    frontend:
      scheduler_address: ""
      tail_proxy_url: ""
    frontend_worker:
      scheduler_address: ""
    index_gateway:
      mode: simple
    limits_config:
      allow_structured_metadata: false
      ingestion_burst_size_mb: 1000
      ingestion_rate_mb: 10000
      max_cache_freshness_per_query: 10m
      query_timeout: 300s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
      volume_enabled: true
    memberlist:
      join_members:
      - loki-memberlist
    pattern_ingester:
      enabled: false
    query_range:
      align_queries_with_step: true
    ruler:
      enable_api: true
      remote_write:
        client:
          url: http://prometheus-prometheus.monitoring:9090/api/v1/write
        enabled: true
      ring:
        kvstore:
          store: inmemory
      rule_path: /tmp/loki/rules
      storage:
        local:
          directory: /var/loki/rules
        type: local
      wal:
        dir: /tmp/loki/wal
    runtime_config:
      file: /etc/loki/runtime-config/runtime-config.yaml
    schema_config:
      configs:
      - from: "2024-10-01"
        index:
          period: 24h
          prefix: index_
        object_store: gcs
        schema: v13
        store: tsdb
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
      http_server_read_timeout: 600s
      http_server_write_timeout: 600s
    storage_config:
      bloom_shipper:
        working_directory: /var/loki/data/bloomshipper
      boltdb_shipper:
        index_gateway_client:
          server_address: ""
      gcs:
        bucket_name: admf-new-loyalty-prod
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
      tsdb_shipper:
        active_index_directory: /tmp/loki/index
        cache_location: /tmp/loki/index_cache
        index_gateway_client:
          server_address: ""
    tracing:
      enabled: false
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: loki-single
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2024-11-13T07:49:59Z"
  labels:
    app.kubernetes.io/instance: loki-single
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.2.0
    helm.sh/chart: loki-6.19.0
  name: loki
  namespace: monitoring
  resourceVersion: "49673447"
  uid: 65ed4eb6-1f1d-4bfb-8603-9461d995b906
