apiVersion: v1
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: "http://loki-single:3100"
      version: 1
      isDefault: true
      jsonData:
        {}
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: loki-single
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2024-11-08T07:55:56Z"
  labels:
    app: loki-stack
    app.kubernetes.io/managed-by: Helm
    chart: loki-stack-2.10.2
    grafana_datasource: "1"
    heritage: Helm
    release: loki-single
  name: loki-single-loki-stack
  namespace: monitoring
  resourceVersion: "21973313"
  uid: d4fc3212-3339-4884-8a0a-28957a2e6e05
