apiVersion: v1
data:
  master.conf: |-
    dir /data
    # User-supplied master configuration:
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    # End of master configuration
  redis.conf: |-
    # User-supplied common configuration:
    appendonly yes
    save ""
    # End of common configuration
  replica.conf: |-
    dir /data
    # User-supplied replica configuration:
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    # End of replica configuration
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: redis-standalone
    meta.helm.sh/release-namespace: prod
  creationTimestamp: "2024-11-15T08:10:11Z"
  labels:
    app.kubernetes.io/instance: redis-standalone
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.4.1
    helm.sh/chart: redis-20.3.0
  name: redis-standalone-configuration
  namespace: prod
  resourceVersion: "29497030"
  uid: 4c51ad0e-6700-41fe-82ec-bd8c1683741d
